#!/bin/bash
## itunes
## version 0.0.1 - initial
##################################################
. ${SH2}/aliases/commands.sh
powershell() {
  command powershell -noprofile -
}
ps1-current-track() { 
  cat << EOF
${itunes}.CurrentTrack.Name
EOF
}
ps1-next-track() {
  cat << EOF
${itunes}.nextTrack()
EOF
}
ps1() { 
  cat << EOF
#Create iTunes Object
${itunes} = New-Object -ComObject iTunes.Application
EOF
  commands
}
itunes-current-track() {
  ps1 current-track
}
itunes-next-track() {
  ps1 next-track 
}
itunes() {
  local itunes='${itunes}'
  {
    commands
  } | powershell
}
##################################################
if [ ! ] 
then
 true
else
 exit 1 # wrong args
fi
##################################################
itunes ${@}
##################################################
## generated by create-stub2.sh v0.1.2
## on Wed, 11 Dec 2019 10:03:47 +0900
## see <https://github.com/temptemp3/sh2>
##################################################
